//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reactive.RiaServices.Samples
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// Context for the RIA application.
    /// </summary>
    /// <remarks>
    /// This context extends the base to make application services and types available
    /// for consumption from code and xaml.
    /// </remarks>
    public sealed partial class WebContext : WebContextBase
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the WebContext class.
        /// </summary>
        public WebContext()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the context that is registered as a lifetime object with the current application.
        /// </summary>
        /// <exception cref="InvalidOperationException"> is thrown if there is no current application,
        /// no contexts have been added, or more than one context has been added.
        /// </exception>
        /// <seealso cref="System.Windows.Application.ApplicationLifetimeObjects"/>
        public new static WebContext Current
        {
            get
            {
                return ((WebContext)(WebContextBase.Current));
            }
        }
    }
}
namespace Reactive.RiaServices.Samples.Web.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// The 'Post' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/Reactive.RiaServices.Samples.Web.Model")]
    public sealed partial class Post : Entity
    {
        
        private int _id;
        
        private string _text;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnTextChanging(string value);
        partial void OnTextChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Post"/> class.
        /// </summary>
        public Post()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'Id' value.
        /// </summary>
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [ReadOnly(true)]
        [RoundtripOriginal()]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnIdChanging(value);
                    this.ValidateProperty("Id", value);
                    this._id = value;
                    this.RaisePropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Text' value.
        /// </summary>
        [DataMember()]
        public string Text
        {
            get
            {
                return this._text;
            }
            set
            {
                if ((this._text != value))
                {
                    this.OnTextChanging(value);
                    this.RaiseDataMemberChanging("Text");
                    this.ValidateProperty("Text", value);
                    this._text = value;
                    this.RaiseDataMemberChanged("Text");
                    this.OnTextChanged();
                }
            }
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._id;
        }
    }
}
namespace Reactive.RiaServices.Samples.Web.Service
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    using System.ServiceModel.Web;
    using Reactive.RiaServices.Samples.Web.Model;
    
    
    /// <summary>
    /// The DomainContext corresponding to the 'PostDomainService' DomainService.
    /// </summary>
    public sealed partial class PostDomainContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="PostDomainContext"/> class.
        /// </summary>
        public PostDomainContext() : 
                this(new WebDomainClient<IPostDomainServiceContract>(new Uri("Reactive-RiaServices-Samples-Web-Service-PostDomainService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="PostDomainContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The PostDomainService service URI.</param>
        public PostDomainContext(Uri serviceUri) : 
                this(new WebDomainClient<IPostDomainServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="PostDomainContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public PostDomainContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the set of <see cref="Post"/> entity instances that have been loaded into this <see cref="PostDomainContext"/> instance.
        /// </summary>
        public EntitySet<Post> Posts
        {
            get
            {
                return base.EntityContainer.GetEntitySet<Post>();
            }
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Post"/> entity instances using the 'LoadPosts' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Post"/> entity instances.</returns>
        public EntityQuery<Post> LoadPostsQuery()
        {
            this.ValidateMethod("LoadPostsQuery", null);
            return base.CreateQuery<Post>("LoadPosts", null, false, true);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetPredefinedPost' method of the DomainService.
        /// </summary>
        /// <param name="callback">Callback to invoke when the operation completes.</param>
        /// <param name="userState">Value to pass to the callback.  It can be <c>null</c>.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<Post> GetPredefinedPost(Action<InvokeOperation<Post>> callback, object userState)
        {
            this.ValidateMethod("GetPredefinedPost", null);
            return ((InvokeOperation<Post>)(this.InvokeOperation("GetPredefinedPost", typeof(Post), null, true, callback, userState)));
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetPredefinedPost' method of the DomainService.
        /// </summary>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<Post> GetPredefinedPost()
        {
            this.ValidateMethod("GetPredefinedPost", null);
            return ((InvokeOperation<Post>)(this.InvokeOperation("GetPredefinedPost", typeof(Post), null, true, null, null)));
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new PostDomainContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'PostDomainService' DomainService.
        /// </summary>
        [ServiceContract()]
        public interface IPostDomainServiceContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'GetPredefinedPost' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/PostDomainService/GetPredefinedPostDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/PostDomainService/GetPredefinedPost", ReplyAction="http://tempuri.org/PostDomainService/GetPredefinedPostResponse")]
            IAsyncResult BeginGetPredefinedPost(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetPredefinedPost'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetPredefinedPost'.</param>
            /// <returns>The 'Post' returned from the 'GetPredefinedPost' operation.</returns>
            Post EndGetPredefinedPost(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'LoadPosts' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/PostDomainService/LoadPostsDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/PostDomainService/LoadPosts", ReplyAction="http://tempuri.org/PostDomainService/LoadPostsResponse")]
            [WebGet()]
            IAsyncResult BeginLoadPosts(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginLoadPosts'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginLoadPosts'.</param>
            /// <returns>The 'QueryResult' returned from the 'LoadPosts' operation.</returns>
            QueryResult<Post> EndLoadPosts(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'SubmitChanges' operation.
            /// </summary>
            /// <param name="changeSet">The change-set to submit.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/PostDomainService/SubmitChangesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/PostDomainService/SubmitChanges", ReplyAction="http://tempuri.org/PostDomainService/SubmitChangesResponse")]
            IAsyncResult BeginSubmitChanges(IEnumerable<ChangeSetEntry> changeSet, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginSubmitChanges'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginSubmitChanges'.</param>
            /// <returns>The collection of change-set entry elements returned from 'SubmitChanges'.</returns>
            IEnumerable<ChangeSetEntry> EndSubmitChanges(IAsyncResult result);
        }
        
        internal sealed class PostDomainContextEntityContainer : EntityContainer
        {
            
            public PostDomainContextEntityContainer()
            {
                this.CreateEntitySet<Post>(EntitySetOperations.All);
            }
        }
    }
}
